"""first migration

Revision ID: a5bed5e15244
Revises: 
Create Date: 2024-08-12 01:54:22.457710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bed5e15244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.drop_constraint('provider_provider_uuid_key', type_='unique')
        batch_op.drop_constraint('provider_user_id_key', type_='unique')
        batch_op.drop_constraint('unique_provider', type_='unique')
        batch_op.create_unique_constraint('unique_provider', ['provider_name', 'provider_uuid'])
        batch_op.drop_constraint('provider_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'provider', ['provider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('provider_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_constraint('unique_provider', type_='unique')
        batch_op.create_unique_constraint('unique_provider', ['user_id', 'provider_name', 'provider_uuid'])
        batch_op.create_unique_constraint('provider_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('provider_provider_uuid_key', ['provider_uuid'])

    # ### end Alembic commands ###
